openapi: 3.0.3
info:
  title: Your Project API
  version: 1.0.0
  description: Your project description
paths:
  /api/phonebook/:
    get:
      operationId: root_retrieve
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PhoneBook'
          description: ''
    post:
      operationId: root_create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PhoneBook'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PhoneBook'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PhoneBook'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PhoneBook'
          description: ''
    patch:
      operationId: root_partial_update
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPhoneBook'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedPhoneBook'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedPhoneBook'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PhoneBook'
          description: ''
    delete:
      operationId: root_destroy
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /api/phonebook/{number}:
    get:
      operationId: root_retrieve_2
      parameters:
      - in: path
        name: number
        schema:
          type: string
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PhoneBook'
          description: ''
components:
  schemas:
    PatchedPhoneBook:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        number:
          type: string
          maxLength: 100
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        is_blacklisted:
          type: boolean
    PhoneBook:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        number:
          type: string
          maxLength: 100
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
        is_blacklisted:
          type: boolean
      required:
      - created_at
      - id
      - number
      - updated_at
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
