# Generated by Django 4.2.6 on 2023-10-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(default='', max_length=100)),
                ('is_blacklisted', models.BooleanField(default='white', max_length=100)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
